development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: test
  pool: 5
  username: root
  password: fankai
  host: localhost
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: test
  pool: 200
  username: root
  password: fankai
  host: localhost
